### ISSUE TITLE
Maybe performance issue related are to Xcode Scheme Settings

### ISSUE THREAD

**Issue by ludagoo** [eldade/ios_metal_bezier_renderer#2]
I wander if the performance issues you are encountering are related to this:
[Xcode Scheme Settings and Performance](https://developer.apple.com/library/content/documentation/Miscellaneous/Conceptual/MetalProgrammingGuide/Dev-Technique/Dev-Technique.html#//apple_ref/doc/uid/TP40014221-CH8-SW3)

> When a Metal app is running from Xcode, the default scheme settings reduce performance. Xcode detects whether the Metal API is used in the source code and automatically enables the GPU Frame Capture and Metal API Validation settings, as seen in Figure 8-2. When GPU Frame Capture is enabled, the debug layer is activated. When Metal API Validation is enabled, each call is validated, which affects performance further. For both settings, CPU performance is more affected than GPU performance. Unless you disable these settings, app performance may noticeably improve when the app is run outside of Xcode.

**Comment by eldade** [comment]
Thanks @ludagoo 

I do not believe this is CPU-bound at all, I think as you increase the number of curves, the bottleneck is the GPU (specifically the pixel fillrate since it's overwriting all those curves for each frame). The most meaningful likely improvement is to add a depth or stencil buffer that'll prevent all this overdrawing. Have you tried just running it without the debug checks?

**Comment by ludagoo** [comment]
Yes it does not improve things noticeably.
